/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ıkinci_donem_hafta_bes;

/**
 *
 * @author nilin
 */
public class Ex1 extends javax.swing.JFrame { //il olarak kabul et ve içinde olan değişken
    //global değişkendir.
    //içine yazılan if for metotları mahalle oluyor.
    //global değişken class içinde yazılırsa her yerde kullanılır.
    int sayac = 0;
    

    /**
     * Creates new form Ex1
     */
    public Ex1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_arttır = new javax.swing.JButton();
        btn_azalt = new javax.swing.JButton();
        lbl_txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_arttır.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_arttır.setText("Arttır");
        btn_arttır.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_arttırActionPerformed(evt);
            }
        });

        btn_azalt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_azalt.setText("Azalt");
        btn_azalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_azaltActionPerformed(evt);
            }
        });

        lbl_txt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbl_txt.setText("    0");
        lbl_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btn_arttır)
                .addGap(41, 41, 41)
                .addComponent(lbl_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btn_azalt)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_arttır)
                    .addComponent(btn_azalt))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_arttırActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_arttırActionPerformed
        //mahalle içinde tanımlanan değişkenler dışarda kullanılamaz.
        sayac++;
        lbl_txt.setText(String.valueOf(sayac));
        
    }//GEN-LAST:event_btn_arttırActionPerformed

    private void btn_azaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_azaltActionPerformed
       sayac--;
       lbl_txt.setText(String.valueOf(sayac));
    }//GEN-LAST:event_btn_azaltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_arttır;
    private javax.swing.JButton btn_azalt;
    private javax.swing.JLabel lbl_txt;
    // End of variables declaration//GEN-END:variables
}
