package ıkinci_donem_hafta_bes;

import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author nilin
 */
public class Sayısal_loto extends javax.swing.JFrame {

    int[] sayisalloto = new int[6];
    int[] girilensayi = new int[6];

    /**
     * Creates new form Sayısal_loto
     */
    public Sayısal_loto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        lbl_bir = new javax.swing.JLabel();
        lbl_iki = new javax.swing.JLabel();
        lbl_uc = new javax.swing.JLabel();
        lbl_dort = new javax.swing.JLabel();
        lbl_bes = new javax.swing.JLabel();
        lbl_alti = new javax.swing.JLabel();
        btn_uret = new javax.swing.JButton();
        lbl_loto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_sayi = new javax.swing.JTextField();
        btn_ekle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_sayi = new javax.swing.JList<>();
        btn_kontrol = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_bir.setText("        ");
        lbl_bir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_iki.setText("  ");
        lbl_iki.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_uc.setText("    ");
        lbl_uc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_dort.setText("   ");
        lbl_dort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_bes.setText("    ");
        lbl_bes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_alti.setText("   ");
        lbl_alti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btn_uret.setText("ÜRET");
        btn_uret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uretActionPerformed(evt);
            }
        });

        lbl_loto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_loto.setText("SAYISAL LOTO ÇEKİLİŞİ");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        txt_sayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sayiActionPerformed(evt);
            }
        });

        btn_ekle.setText("EKLE");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list_sayi);

        btn_kontrol.setText("KONTROL");
        btn_kontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kontrolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ekle)
                    .addComponent(txt_sayi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_kontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_kontrol))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_sayi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ekle)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lbl_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lbl_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_loto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbl_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(lbl_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(lbl_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btn_uret, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_loto)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btn_uret, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static int indexOfIntArray(int[] array, int key) {
        int returnvalue = -1;
        for (int i = 0; i < array.length; ++i) {
            if (key == array[i]) {
                returnvalue = i;
                break;
            }
        }
        return returnvalue;
    }

    private void btn_uretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uretActionPerformed
        Random r = new Random();
        for (int i = 0; i < sayisalloto.length; i++) {
            int temp = r.nextInt(49 - 1 + 1) + 1; //min=1 & max=49; randomint(max-min+1)+min
            if (indexOfIntArray(sayisalloto, temp) == -1) {
                sayisalloto[i] = temp;
            }

        }
        lbl_bir.setText(String.valueOf(sayisalloto[0]));//stringe dönüştürüp atama işlemi set text(atama)
        lbl_iki.setText(String.valueOf(sayisalloto[1]));//stringe dönüştürüp atama işlemi
        lbl_uc.setText(String.valueOf(sayisalloto[2]));//stringe dönüştürüp atama işlemi
        lbl_dort.setText(String.valueOf(sayisalloto[3]));//stringe dönüştürüp atama işlemi
        lbl_bes.setText(String.valueOf(sayisalloto[4]));//stringe dönüştürüp atama işlemi
        lbl_alti.setText(String.valueOf(sayisalloto[5]));//stringe dönüştürüp atama işlemi

    }//GEN-LAST:event_btn_uretActionPerformed
    int sayac = 0;
    DefaultListModel demoList = new DefaultListModel();
/*
    static int check_txt(javax.swing.JTextField txt)
    int temp;
     try {  //hata oluşabilecek yerleri try içine yazıyoruz.
     temp=Integer.parseInt(txt_sayi.getText()); 
    return temp;
        }
        catch (Expection ex) { //hata olursa yapılacak şeyi catch içine yazıyoruz.
        
        JOptionPane.showMessageDialog(null, "Lütfen sayısal değer giriniz.");
        return 0; 
    */
    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        /*
     int temp;
     try {  //hata oluşabilecek yerleri try içine yazıyoruz.
     temp=Integer.parseInt(txt_sayi.getText()); 
        }
        catch (Expection ex) { //hata olursa yapılacak şeyi catch içine yazıyoruz.
        
        //JOptionPane.showMessageDialog(null, ex.toString());
        
        JOptionPane.showMessageDialog(null, "Lütfen sayısal değer giriniz.");
        return; //çalışma durur ve devamındaki kodu çalıştırmaz.
         */
        /*
        int temp = check_txt(txt_sayi);
        if(temp==0) {
        
        */
        int temp = Integer.parseInt(txt_sayi.getText());
        if (indexOfIntArray(girilensayi, temp) == -1 && sayac < girilensayi.length) {
            girilensayi[sayac] = temp;
            demoList.addElement(girilensayi[sayac]);
            list_sayi.setModel(demoList);
            sayac++;
        } else {
            JOptionPane.showMessageDialog(null, "Lütfen girilen sayı ve miktarını kontrol ediniz!");
        }

        if (sayac == 6) {
            btn_uret.setEnabled(true);
        }


    }//GEN-LAST:event_btn_ekleActionPerformed

    private void btn_kontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kontrolActionPerformed
        int ortak = 0;
        for (int i = 0; i < sayisalloto.length; i++) {
            for (int j = 0; j < girilensayi.length; j++) {
                if (sayisalloto[i] == girilensayi[j]) {
                    ortak++;
                }
            }
        }
        JOptionPane.showMessageDialog(null, ortak + " kadar sayı bildiniz");

    }//GEN-LAST:event_btn_kontrolActionPerformed

    private void txt_sayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sayiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sayiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sayısal_loto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sayısal_loto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sayısal_loto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sayısal_loto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sayısal_loto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton btn_kontrol;
    private javax.swing.JButton btn_uret;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_alti;
    private javax.swing.JLabel lbl_bes;
    private javax.swing.JLabel lbl_bir;
    private javax.swing.JLabel lbl_dort;
    private javax.swing.JLabel lbl_iki;
    private javax.swing.JLabel lbl_loto;
    private javax.swing.JLabel lbl_uc;
    private javax.swing.JList<String> list_sayi;
    private javax.swing.JTextField txt_sayi;
    // End of variables declaration//GEN-END:variables
}
