
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nilin
 */
public class Odev extends javax.swing.JFrame {

    /**
     * Creates new form Odev
     */
    public Odev() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_tc = new javax.swing.JTextField();
        bt_dogrula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("TC KİMLİK NO DOĞRULAMA");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("TC GİRİNİZ : ");

        txt_tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tcActionPerformed(evt);
            }
        });

        bt_dogrula.setText("DOĞRULA");
        bt_dogrula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dogrulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42)
                                .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(bt_dogrula, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_dogrula, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txt_tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tcActionPerformed

    private void bt_dogrulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dogrulaActionPerformed
        String tcno = txt_tc.getText();
        double sayi;

        double sayii;
        try {
            sayii = Double.parseDouble(txt_tc.getText());
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Lütfen sayısal değer giriniz.");
            return;
        }

        if (tcno.length() != 11) {
            JOptionPane.showMessageDialog(null, "TCno 11 haneli olmalı.");
        } else {
            int toplam = 0;
            for (int i = 0; i < tcno.length() - 1; i++) {
                toplam += Integer.parseInt(String.valueOf(tcno.charAt(i)));
            }
            if (toplam % 10 == Integer.parseInt(String.valueOf(tcno.charAt(10)))) {
                JOptionPane.showMessageDialog(null, "TC no geçerlidir.");
            } else {
                JOptionPane.showMessageDialog(null, "TC no geçersizdir.");
            }
        }

    }

    /**
     * int tc = Integer.parseInt(txt_tc.getText()); double onuncu = 0; double
     * onbirinci=0; double ilkdokuz = 0; double toplam = 0; for (int i = 0; i <
     * 10; i++) { ilkdokuz += tc % 10; //sağdaki basamağı toplama ekle tc = tc /
     * 10; //sağdaki basamağı sil } for (int i = 0; i < 8; i+=2) { onuncu += tc
     * % 10; //sağdaki basamağı toplama ekle tc = tc / 10; //sağdaki basamağı
     * sil
     *
     * }
     * for (int i = 0; i < 7; i+=2) { toplam += tc % 10; //sağdaki basamağı
     * toplama ekle tc = tc / 10; //sağdaki basamağı sil } onuncu=onuncu*7;
     * onuncu=(onuncu-toplam)/10; onbirinci=(onuncu+ilkdokuz)/10; if
     * ((tc/(1000*1000*1000*10)==onuncu) &&
     * (tc/(1000*1000*1000*100)==onbirinci)) {
     * JOptionPane.showMessageDialog(null,"Doğru TC"+tc); } else {
     * JOptionPane.showMessageDialog(null,"Geçersiz TC"); }
    }//GEN-LAST:event_bt_dogrulaActionPerformed
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Odev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Odev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Odev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Odev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Odev().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_dogrula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_tc;
    // End of variables declaration//GEN-END:variables
}
